# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('specialization', models.CharField(max_length=255)),
                ('end_point', models.TextField(null=True)),
                ('limit_sec', models.IntegerField(default=-1)),
                ('limit_min', models.IntegerField(default=-1)),
                ('limit_hour', models.IntegerField(default=-1)),
                ('limit_week', models.IntegerField(default=-1)),
                ('limit_month', models.IntegerField(default=-1)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'db_table': 'rate_limit_config_all',
            },
        ),
    ]
